### ISSUE TITLE
Support for glTF format

### ISSUE THREAD

**Issue by addy1997** [gazebo-web/gzweb#49]
Hi @german-e-mas,

Does gzweb support 3D models with **.glTF** format?

**Comment by addy1997** [comment]
> Hello @addy1997 . No, it doesn't support it yet.
> 
> To do so, we would need to include [ThreeJS's GLTFLoader](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/GLTFLoader.js) and use it whenever we read a gltf file when constructing the scene.

Hi @german-e-mas,

So, do you mean that I should include the [ColladaLoader.js](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/ColladaLoader.js#L412) to the /include directory (of this project) and modify the [Scene.ts](https://github.com/gazebo-web/gzweb/blob/gzweb2/src/Scene.ts) file? Will this work?

**Comment by german-e-mas** [comment]
Just in case, you sent the link to the ColladaLoader, which handles `.dae` files. You want a GLTFLoader.

That would allow ThreeJS to properly interpret the files. But in gzweb we need to parse an asset's SDF before adding it to the scene. You have to make sure meshes are loaded properly.

**Comment by addy1997** [comment]
> Just in case, you sent the link to the ColladaLoader, which handles `.dae` files. You want a GLTFLoader.
> 
> That would allow ThreeJS to properly interpret the files. But in gzweb we need to parse an asset's SDF before adding it to the scene. You have to make sure meshes are loaded properly.

Oh! Sorry! Yes, I want the GLTFLoader.js file. So, I'll have to change the Scene.ts and SDF.parser files. Which files am I supposed to change to load GLTF models?
