### ISSUE TITLE
Where is the run script?

### ISSUE THREAD

**Issue by ctyler9** [gazebo-web/gzweb#58]
sorry if this sounds dumb, i don't do too much front end work. I was able to build the app and get the tests to pass, but i can't seem to run it. there is no run script in the package.json and i tried running node index.js and even in the compiled dist directory without any luck. just trying to get it to run like the classic gzweb version. thanks!

**Comment by german-e-mas** [comment]
Hello @ctyler9 . You can't use this on its own. This is a library meant to be consumed by frontend applications. You can see an example of how to use it here: https://github.com/german-e-mas/angular-gzweb.

**Comment by ctyler9** [comment]
ah thank you! makes much more sense
